# Generated by Django 5.2.1 on 2025-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourorganization',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
