# Generated by Django 5.2.1 on 2025-05-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0002_ourorganization_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
