# Generated by Django 5.2.1 on 2025-05-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0003_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField()),
                ('document_date', models.DateTimeField(auto_now_add=True)),
                ('ourorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment1', to='testpayment.ourorganization')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
