# Generated by Django 5.2.1 on 2025-05-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ourorg',
        ),
    ]
