# Generated by Django 5.2.1 on 2025-05-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0005_remove_payment_operation_id_remove_payment_ourorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='counterorg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment2', to='testpayment.counterorganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='document_number',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_id',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='ourorg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment1', to='testpayment.ourorganization'),
            preserve_default=False,
        ),
    ]
