# Generated by Django 5.2.1 on 2025-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0006_payment_amount_payment_counterorg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField()),
                ('amount', models.PositiveIntegerField()),
                ('document_number', models.CharField()),
                ('document_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Банковский Платеж',
                'verbose_name_plural': 'Банковские Платежи',
            },
        ),
    ]
