# Generated by Django 5.2.1 on 2025-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0007_bankpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='operation_id',
            field=models.CharField(unique=True),
        ),
    ]
