# Generated by Django 5.2.1 on 2025-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0008_alter_bankpayment_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='payer_inn',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
