# Generated by Django 5.2.1 on 2025-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0009_bankpayment_payer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='payer_inn',
            field=models.CharField(),
        ),
    ]
