# Generated by Django 5.2.1 on 2025-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpayment', '0010_alter_bankpayment_payer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterorganization',
            name='inn',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
